RTS:
    wsTransformer: websockets // be advised that faye strips js types
    dbApi: ./app/rts-sql-api
    dbConfig: 
        server: crane.saccounty.net
            database: RTS
            user: sql-rtswebservice
            password: stored locally
            port: 1433
        log:
            level: trace
            levels:
                emergency: 0
                error: 3
                warning: 4
                info: 6
                debug: 7
                trace: 8
            colors:
                emergency: red
                error: red
                warn: yellow
                info: white
                debug: green
                trace: blue
AGENDA: 
    restApi: ./app/sire-rest-api
    dbApi: ./app/sire-js-api
        dbConfig: 
            server: heron.saccounty.net
            database: SIRE
            user: sql-rtswebservice
            password: stored locally
            port: 1433
AUTH:
    restApi: ./app/auth-rest-api
    users: 
        - user: abc@saccounty.net
            groups: [wall]
        - user: def@saccounty.net
            groups: [kiosk]
        - user: 123@saccounty.net
            groups: [admin]
        - user: 456@saccounty.net
            groups: [board]]